### ISSUE TITLE
Dev-diplodocus & GDAL support

### ISSUE THREAD

**Issue by illpack** [GeographicaGS/Docker-PostGIS#60]
I ran into problems while trying to run my local `ogr2ogr` on the Docker's port - versioning problem. 
Solution: include supported versions of GDAL in the Docker-compose definition:

```yml
version: "3"
services:
  postgis:
    image: geographica/postgis:dev_diplodocus
    ports:
      - "5433:5432"
    volumes:
      - ./db-data:/data
    environment:
      - POSTGRES_PASSWD=postgres
  gdal:
    image: geographica/gdal2:2.4.3
    volumes:
      - ./:/data
    command:
      - sleep
      - 999d
```

This will ensure compatibility (worked for me at least!) and then you'll be able to run `ogr2ogr` from the container, and point towards the `postgis` container on the localhost:

```bash
ogr2ogr -f 'PostgreSQL' PG:"host=postgis port=5432 dbname=dbname user=postgres password=XXXXXX" ${FILEPATH} -nln schema.component --config PG_USE_COPY YES -progress -nlt PROMOTE_TO_MULTI -lco PRECISION=NO
```
cheers mighty @ManuelLR for the fix
